### ISSUE TITLE
move to poetry

### ISSUE THREAD

**Issue by xmonader** [xmonader/pygundb#29]

**Comment by bitnom** [comment]
Please keep a redundant requirements or Pipfile file so that Jetbrains projects have something to work with. Poetry is not yet working in IDEA.

**Comment by xmonader** [comment]
@TensorTom I added requirments.txt task `make requirements.txt` should generate you one `added by default in the repo now`

cff9ef51c3d8b02f0331e776a86e9734680efd4f
