### ISSUE TITLE
Jetbrains Intellij IDEA / PyCharm

### ISSUE THREAD

**Issue by bitnom** [xmonader/pygundb#30]
How can I import pygundb such that IDEA and PyCharm will recognize it? I cloned the repo and tried `import pygundb` but it doesn't see it. I also tried to install it as a module with `pip install -e` but that failed.

![IDEA not recognizing module](https://i.imgur.com/61EFEQq.png)

**Comment by xmonader** [comment]
It should be imported as `gundb` not pygundb I think I should rename the repo.

there're 2 files in the root of the repo we provide as example for usage/starting servers flask server `app.py` and gevent server `geventapp.py` choose the suitable one for your and run it using our Makefile or build your custom servers if you wish

**Comment by bitnom** [comment]
Thanks. No need to change the repo name. Would be cool if you upload to pypi and an example though.
