### ISSUE TITLE
Docs link 404s

### ISSUE THREAD

**Issue by westurner** [xmonader/pygundb#31]
https://xmonader.github.io/pygundb/api/gundb/ -> 404

https://xmonader.github.io/pygundb/ -> 404

**Comment by xmonader** [comment]
thanks for reporting
https://xmonader.github.io/pygundb/docs/api/gundb/index.html

and the other one should show you the READM.md

**Comment by westurner** [comment]
https://xmonader.github.io/pygundb/docs/api/gundb/ also works.

Any reason the gh-pages root path isn't just set to docs/API/gundb so that
https://xmonader.github.io/pygundb/ works?

**Comment by westurner** [comment]
https://xmonader.github.io/pygundb/docs/api/gundb/ also works.

~~Any reason the gh-pages root path isn't just set to docs/API/gundb so that
https://xmonader.github.io/pygundb/ works?~~
